sudo: required
services:
    - docker

before_install:
    - docker build -t mariof2/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mariof2/docker-react npm run test -- --coverage
